FROM ubuntu:latest

FROM node:lts

WORKDIR /app

COPY package.json .

RUN npm install --force
RUN npm install -g typescript
RUN apt-get update -y
RUN apt-get install -y htop
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]